version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-anime-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: anime_db
    networks:
      - anime-network

  prisma:
    build:
      context: ./anime-review-prisma-orm
      dockerfile: Dockerfile
    container_name: prisma-service
    depends_on:
      - postgres-db
    env_file:
      - ./anime-review-prisma-orm/.env
    ports:
      - 5555:5555
    networks:
      - anime-network

  api:
    build:
      context: ./anime-review-api
      dockerfile: Dockerfile
    container_name: anime-review-api
    depends_on:
      - prisma
      - postgres-db
    ports:
      - 8080:8080
    networks:
      - anime-network

  web:
    depends_on:
      - api
    build:
      context: ./anime-review-client
      dockerfile: Dockerfile
    container_name: anime-review-client
    ports:
      - 5173:5173

networks:
  anime-network:
    driver: bridge