version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-anime-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: anime_db