version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: anime_db